insert into article (title, content, author, created_at, updated_at) values ('제목1', '내용1', 'user1', NOW(), NOW())
insert into comments (article_id, author, content, created_at) values (1,'user4','댓글1',NOW())
insert into comments (article_id, author, content, created_at) values (1,'user5','댓글2',NOW())
insert into article (title, content, author, created_at, updated_at) values ('제목2', '내용2', 'user2', NOW(), NOW())
insert into article (title, content, author, created_at, updated_at) values ('제목3', '내용3', 'user3', NOW(), NOW())
